### ISSUE TITLE
Събиране на ключовете на екипа

### ISSUE THREAD

**Issue by robotpanic** [OpenFest/openfest-network-2018#8]

**Comment by robotpanic** [comment]
Да се съберат SSH-ключовете на екипа

**Comment by Yasen6275** [comment]
https://bigbro.uni-sofia.bg/Yasen6275_2.key

**Comment by Arcopix** [comment]
Stefan Lekov / https://load.devhex.org/key/stefan.key

**Comment by robotpanic** [comment]
Kalin Iliev

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCz95lRGXJWd1dJW0IW22hlgQLIgMDbTad2qzmatvahyLeSXOSXstZMs9XRKYCHyC5bUYj4WipUho/tV4nBcqHkP70TMMCHMQMUvEE/cRVQ7pCiP1+1yV8QCHEe3SvAxcppfxvpU/Znt7R5gV3siL2G47UuWr5OiNj9rPxON9/qK/qBX+G09dE3pLWkBuRpSMXxP5aY4GW0gduHSCR4mPaVrnikLuXrbTcWzCXwCUK6eJzj2LQFY1V0TOgstiNa3TsKtMNbh7JJongPYDRZhYhUD36OuWfAO4be38tWxyIccoy3x2rz8xIavxTzSpponWr12O12RjRyzp8YLSQJbDsx eric

**Comment by Yasen6275** [comment]
Извинявам се зa неудобството но се наложи да сменя ключовете си и забравих erik2. Не са компрометирани, причините са други. Та ако може някой да ми смени ключа на ерик2 с този:

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIw9VEb7HIABBieys5VLSM7pfpQRYeiKytaNt5PT7Zu0 Yasen6275

**Comment by zeridon** [comment]
Готово

**Comment by hackman** [comment]
http://hydra.azilian.net/hackman.pub

**Comment by zeridon** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAkwF4e84AuzUyoGww6T/Nlt3VFAl9kQpTsc9TdVXo9bZa93io3FhGjuY/DFxh9vS3BzWsESTVyMXlPUbBYadUXAf0jTs+xKkIGqdG/or/d4pJ6UcKlYcOq3CxGozMjnP7CQLbYXG6j6u+RRTvmIpaOiSE87m5+i5uRCyZSH+1EDMdh1LyXNFcy5LMQspceNBLgBoyhuGMFxWrLWli7pzaXLrAuDWO9GQn2RZhIZsZ6stCMlHne4HM/c6MhqEF8/b4iviBTdKyOo/GoWk3W8vf1fg3W+UKYLkWo9jrVtINjCbcJIxmyZM+AbklkZEpn/Y8GFNZQy8UENbD2RXpvpryup0JBWLgxrC54VFF2HUSSEHAGe9J3+SqKs2VwmIV9FuyC5+VrnA0VnhJvurPIeVoINAlkFz+sU7Ocoxt+qNgZsFGnum0iH3IvugDaSPx313i/BPusIeCNbN5B3fI6rBkmEcjIRC+RQj4o4tLOIYrykqBqKX3FnAmDEEGP5RhmltaXdryi5/ae9I29XtMgen1oH9cGK8o/6O/9+8Qeuf6uupZ7GiQPWWN/NHCdDSA6Rd0V3GnZK3G2H1djc4t/CceK9k2YoHClzrrx53AWDCQfw8sdv9TpZpsH3hj6PZqYS2hlblCpPuThDCWJJ8/LXx1SvLpJXlhFSYnb9yIuOVmj+U= zeridon@p50

**Comment by tit2fan** [comment]
Тишо 
https://office.35910.net/tisho/tisho.key
